# Generated by Django 5.2.14 on 2026-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_serviceusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='صورة الإيصال'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية'),
        ),
    ]
