# Generated by Django 5.2.14 on 2026-05-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_payment_proof_image_payment_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
