# Generated by Django 5.2.13 on 2026-05-26 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=100)),
                ('irr_date', models.DateTimeField(blank=True, null=True)),
                ('fert_date', models.DateTimeField(blank=True, null=True)),
                ('api_data', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
