# Generated by Django 5.2.13 on 2026-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('good', 'Good'), ('medium', 'Medium'), ('danger', 'Danger')], default='info', max_length=20),
        ),
    ]
