# Generated by Django 5.2.13 on 2026-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subscriptionplan_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخصم'),
        ),
    ]
