# Generated by Django 5.2.13 on 2026-07-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_inventoryitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='api.farm'),
        ),
    ]
